// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'

export const AgentAuraSchema = z.object({
  doctrine: z.string().optional(),
  resonance: z.array(z.string()).default([]),
  index: z.array(z.number()).default([]),
})

export type AgentAura = z.infer<typeof AgentAuraSchema>
