// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'
import { AgentAuraSchema } from './agent-aura.js'

export const AgentSchema = z.object({
  kind: z.literal('agent'),
  id: z.string().regex(/^[a-z][a-z0-9-]*$/),
  version: z.string().regex(/^\d+\.\d+\.\d+$/),
  status: z.enum(['draft', 'active', 'deprecated']),
  owner: z.string(),
  tags: z.array(z.string()).default([]),
  description: z.string(),
  tools: z.array(z.string()),
  model: z.enum(['opus', 'sonnet', 'haiku']),
  aura: AgentAuraSchema.optional(),
})

export type AgentSpec = z.infer<typeof AgentSchema>
