// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'

export const BodySectionSchema = z.object({
  heading: z.string(),
  required: z.boolean().default(false),
  reader: z.enum(['plain', 'list', 'table', 'mermaid', 'steps']),
  emits_to: z.string(),
})

export type BodySection = z.infer<typeof BodySectionSchema>
