// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'

export const CommandArgSchema = z.object({
  name: z.string(),
  required: z.boolean().default(false),
  description: z.string().default(''),
})

export type CommandArg = z.infer<typeof CommandArgSchema>
