// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'

export const CommandDeclSchema = z.object({
  name: z.string(),
  args: z.array(z.unknown()).default([]),
  flags: z.array(z.unknown()).default([]),
  description: z.string().default(''),
})

export type CommandDecl = z.infer<typeof CommandDeclSchema>
