// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'

export const ExampleSchema = z.object({
  id: z.string().regex(/^[a-z][a-z0-9-]*$/),
  raw: z.string(),
})

export type Example = z.infer<typeof ExampleSchema>
