// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'

export const FieldSchema = z.object({
  name: z.string(),
  type: z.unknown(),
  required: z.boolean().default(true),
  default: z.unknown().optional(),
  predicate: z.string().optional(),
  description: z.string(),
  examples: z.array(z.unknown()).default([]),
})

export type Field = z.infer<typeof FieldSchema>
