// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'

export const GeneratorDeclSchema = z.object({
  id: z.string().regex(/^[a-z][a-z0-9-]*$/),
  consumes: z.enum(['spec', 'graph', 'meta']),
  output_path: z.string(),
  description: z.string(),
})

export type GeneratorDecl = z.infer<typeof GeneratorDeclSchema>
