// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'

export const HarnessSchema = z.object({
  kind: z.literal('harness'),
  id: z.string().regex(/^[a-z][a-z0-9-]*$/),
  version: z.string().regex(/^\d+\.\d+\.\d+$/),
  status: z.enum(['draft', 'active', 'deprecated']),
  owner: z.string(),
  tags: z.array(z.string()).default([]),
  description: z.string(),
  cron: z.string().optional(),
  dispatches: z.array(z.string().regex(/^[a-z][a-z0-9-]*$/)),
  state_file: z.string(),
  gates: z.array(z.string().regex(/^[a-z][a-z0-9-]*$/)).default([]),
})

export type HarnessSpec = z.infer<typeof HarnessSchema>
