// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'

export const InputDeclSchema = z.object({
  id: z.string().regex(/^[a-z][a-z0-9-]*$/),
  glob: z.string(),
  kinds: z.array(z.string()).default([]),
})

export type InputDecl = z.infer<typeof InputDeclSchema>
