// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'
import { BodySectionSchema } from './body-section.js'
import { CrossRefSchema } from './cross-ref.js'
import { ExampleSchema } from './example.js'
import { FieldSchema } from './field.js'

export const MetaSpecSchema = z.object({
  kind: z.literal('meta-spec'),
  id: z.string().regex(/^[a-z][a-z0-9-]*$/),
  version: z.string().regex(/^\d+\.\d+\.\d+$/),
  status: z.enum(['draft', 'active', 'deprecated']),
  owner: z.string(),
  tags: z.array(z.string()).default([]),
  description: z.string(),
  target_kind: z.string(),
  fields: z.array(FieldSchema).default([]),
  body_layout: z.array(BodySectionSchema).default([]),
  cross_refs: z.array(CrossRefSchema).default([]),
  examples: z.array(ExampleSchema).default([]),
})

export type MetaSpecSpec = z.infer<typeof MetaSpecSchema>
