// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'

export const RalphSchema = z.object({
  kind: z.literal('ralph'),
  id: z.string().regex(/^[a-z][a-z0-9-]*$/),
  version: z.string().regex(/^\d+\.\d+\.\d+$/),
  status: z.enum(['draft', 'active', 'deprecated']),
  owner: z.string(),
  tags: z.array(z.string()).default([]),
  description: z.string(),
  cadence_min: z.number(),
  tick_skill: z.string().regex(/^[a-z][a-z0-9-]*$/),
  report_skills: z.array(z.string().regex(/^[a-z][a-z0-9-]*$/)).default([]),
  pause_flag_path: z.string(),
  circuit_breaker: z.unknown().optional(),
})

export type RalphSpec = z.infer<typeof RalphSchema>
