// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'

export const SkillSchema = z.object({
  kind: z.literal('skill'),
  id: z.string().regex(/^[a-z][a-z0-9-]*$/),
  version: z.string().regex(/^\d+\.\d+\.\d+$/),
  status: z.enum(['draft', 'active', 'deprecated']),
  owner: z.string(),
  tags: z.array(z.string()).default([]),
  description: z.string(),
  argument_hint: z.string().optional(),
  user_invocable: z.boolean(),
  requires_agents: z.array(z.string().regex(/^[a-z][a-z0-9-]*$/)).default([]),
  requires_tools: z.array(z.string()).default([]),
})

export type SkillSpec = z.infer<typeof SkillSchema>
