import { afterAll, describe, expect, test } from 'bun:test'
import { mkdir, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { runApply } from '../src/cli/apply.js'

// runApply resolves SRC_AGENTS/SRC_SKILLS relative to cwd at module load.
// Tests verify return codes based on what's present in the project cwd.

const TMP = join(tmpdir(), `hwh-apply-test-${Date.now()}`)

afterAll(async () => {
  await rm(TMP, { recursive: true, force: true })
})

describe('runApply smoke', () => {
  test('returns a number', async () => {
    // Either 0 (codegen present, dry-run) or 2 (no codegen). Either is valid.
    const code = await runApply([])
    expect(typeof code).toBe('number')
    expect([0, 2]).toContain(code)
  })

  test('dry-run with synthetic codegen dir returns 0', async () => {
    // SRC_AGENTS = resolve('dist', 'codegen', 'agents') from project cwd
    const srcAgents = resolve('dist', 'codegen', 'agents')
    await mkdir(srcAgents, { recursive: true })

    // Write a managed agent stub
    const stubMd = join(srcAgents, 'test-smoke-agent.md')
    await writeFile(
      stubMd,
      '---\nname: test-smoke-agent\n---\n<!-- hwh:managed: do not edit, generated by yhwh -->\n\nBody.',
    )

    try {
      const code = await runApply([])
      expect(typeof code).toBe('number')
      // dry-run (no --apply) prints plan and returns 0
      expect(code).toBe(0)
    } finally {
      // clean up stub to avoid polluting dist
      await rm(stubMd, { force: true })
    }
  })
})
