import type { MetaSpec } from '../schema/index.js'

const HEADER = `// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'`

const sq = (v: string): string => `'${v}'`

const PRIMITIVE_TO_ZOD: Record<string, string> = {
  string: 'z.string()',
  number: 'z.number()',
  boolean: 'z.boolean()',
  'kebab-id': 'z.string().regex(/^[a-z][a-z0-9-]*$/)',
  semver: 'z.string().regex(/^\\d+\\.\\d+\\.\\d+$/)',
  iso8601: 'z.string()',
  glob: 'z.string()',
  unknown: 'z.unknown()',
}

const pascalCase = (s: string): string =>
  s
    .split(/[-_]/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('')

const recordSchemaName = (kind: string): string => `${pascalCase(kind)}Schema`

type Ctx = {
  imports: Set<string>
  selfKind: string
  allKinds: Set<string>
}

const fieldTypeToZod = (type: unknown, predicate: string | undefined, ctx: Ctx): string => {
  if (typeof type === 'string') {
    if (type === 'predicate' && predicate) {
      if (predicate.startsWith('enum:')) {
        const values = predicate.slice(5).split('|')
        return `z.enum([${values.map(sq).join(', ')}])`
      }
      const PREDICATE_TO_ZOD: Record<string, string> = {
        'kebab-id': 'z.string().regex(/^[a-z][a-z0-9-]*$/)',
        semver: 'z.string().regex(/^\\d+\\.\\d+\\.\\d+$/)',
        iso8601:
          'z.string().regex(/^\\d{4}-\\d{2}-\\d{2}(T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?(Z|[+-]\\d{2}:\\d{2})?)?$/)',
        glob: 'z.string().regex(/^[^\\0]+$/)',
      }
      if (predicate in PREDICATE_TO_ZOD) return PREDICATE_TO_ZOD[predicate] as string
      console.warn(`[yhwh codegen-ts] unknown predicate "${predicate}" — emitting z.unknown()`)
      return 'z.unknown()'
    }
    return PRIMITIVE_TO_ZOD[type] ?? 'z.unknown()'
  }
  if (type && typeof type === 'object') {
    const o = type as Record<string, unknown>
    if (typeof o.array === 'string') return `z.array(${fieldTypeToZod(o.array, undefined, ctx)})`
    if (
      o.array &&
      typeof o.array === 'object' &&
      typeof (o.array as Record<string, unknown>).ref === 'string'
    ) {
      const ref = String((o.array as Record<string, unknown>).ref)
      if (ref !== ctx.selfKind && ctx.allKinds.has(ref)) ctx.imports.add(ref)
      return `z.array(${recordSchemaName(ref)})`
    }
    if (typeof o.ref === 'string') {
      const ref = o.ref
      if (ref !== ctx.selfKind && ctx.allKinds.has(ref)) ctx.imports.add(ref)
      return recordSchemaName(ref)
    }
    if (Array.isArray(o.enum) && o.enum.length > 0)
      return `z.enum([${o.enum.map((v: unknown) => sq(String(v))).join(', ')}])`
  }
  return 'z.unknown()'
}

const isArrayType = (type: unknown): boolean =>
  typeof type === 'object' && type !== null && 'array' in (type as Record<string, unknown>)

const wrapField = (
  field: { type?: unknown; required: boolean; default?: unknown; predicate?: string | undefined },
  ctx: Ctx,
): string => {
  const base = fieldTypeToZod(field.type, field.predicate, ctx)
  if (field.required) return base
  if (field.default !== undefined) {
    const def =
      typeof field.default === 'string' ? sq(field.default) : JSON.stringify(field.default)
    return `${base}.default(${def})`
  }
  if (isArrayType(field.type)) return `${base}.default([])`
  return `${base}.optional()`
}

const SPEC_KINDS = new Set([
  'agent',
  'skill',
  'flow',
  'entity',
  'harness',
  'ralph',
  'project',
  'meta-spec',
])

const renderImports = (imports: Set<string>): string =>
  [...imports]
    .sort()
    .map((kind) => `import { ${recordSchemaName(kind)} } from './${kind}.js'`)
    .join('\n')

export const generateRecordModule = (kind: MetaSpec, allKinds: Set<string>): string => {
  const ctx: Ctx = { imports: new Set(), selfKind: kind.target_kind, allKinds }
  const lines = kind.fields
    .filter((f) => f.name !== 'kind')
    .map((f) => `  ${f.name}: ${wrapField(f, ctx)},`)
  const importsBlock = renderImports(ctx.imports)
  const schemaName = recordSchemaName(kind.target_kind)
  const typeName = pascalCase(kind.target_kind)
  const parts: string[] = [HEADER]
  if (importsBlock) parts.push(importsBlock)
  parts.push(
    '',
    `export const ${schemaName} = z.object({`,
    ...lines,
    '})',
    '',
    `export type ${typeName} = z.infer<typeof ${schemaName}>`,
    '',
  )
  return parts.join('\n')
}

export const generateKindModule = (
  envelope: MetaSpec,
  kind: MetaSpec,
  allKinds: Set<string>,
): string => {
  const ctx: Ctx = { imports: new Set(), selfKind: kind.target_kind, allKinds }
  const schemaName = `${pascalCase(kind.target_kind)}Schema`
  const typeName = `${pascalCase(kind.target_kind)}Spec`

  const envelopeLines = envelope.fields
    .filter((f) => f.name !== 'kind')
    .map((f) => `  ${f.name}: ${wrapField(f, ctx)},`)

  const kindLines = kind.fields
    .filter((f) => f.name !== 'kind')
    .map((f) => `  ${f.name}: ${wrapField(f, ctx)},`)

  const importsBlock = renderImports(ctx.imports)
  const parts: string[] = [HEADER]
  if (importsBlock) parts.push(importsBlock)
  parts.push(
    '',
    `export const ${schemaName} = z.object({`,
    `  kind: z.literal(${sq(kind.target_kind)}),`,
    ...envelopeLines,
    ...kindLines,
    '})',
    '',
    `export type ${typeName} = z.infer<typeof ${schemaName}>`,
    '',
  )
  return parts.join('\n')
}

export const generateEnvelopeModule = (envelope: MetaSpec): string => {
  const out: string[] = []
  let kindEnumValues: string[] = []
  let statusEnumValues: string[] = []
  for (const f of envelope.fields) {
    const pred = f.predicate ?? ''
    if (f.name === 'kind' && pred.startsWith('enum:')) kindEnumValues = pred.slice(5).split('|')
    if (f.name === 'status' && pred.startsWith('enum:')) statusEnumValues = pred.slice(5).split('|')
  }

  const kindItems = kindEnumValues.map((v) => `  ${sq(v)},`).join('\n')
  out.push(`export const KIND = z.enum([\n${kindItems}\n])`)
  out.push('export type Kind = z.infer<typeof KIND>')
  out.push('export const ID = z.string().regex(/^[a-z][a-z0-9-]*$/)')
  out.push('export const SEMVER = z.string().regex(/^\\d+\\.\\d+\\.\\d+$/)')
  out.push(`export const STATUS = z.enum([${statusEnumValues.map(sq).join(', ')}])`)

  const shape: string[] = []
  for (const f of envelope.fields) {
    if (f.name === 'kind') {
      shape.push('  kind: KIND,')
      continue
    }
    if (f.name === 'id') {
      shape.push('  id: ID,')
      continue
    }
    if (f.name === 'version') {
      shape.push('  version: SEMVER,')
      continue
    }
    if (f.name === 'status') {
      shape.push('  status: STATUS,')
      continue
    }
    const ctx: Ctx = { imports: new Set(), selfKind: 'envelope', allKinds: new Set() }
    shape.push(`  ${f.name}: ${wrapField(f, ctx)},`)
  }

  return [HEADER, '', ...out, '', 'export const Envelope = z.object({', ...shape, '})', ''].join(
    '\n',
  )
}

export const generateAllModules = (
  envelope: MetaSpec,
  kindMetas: MetaSpec[],
): { kind: string; source: string }[] => {
  const allKinds = new Set(kindMetas.map((m) => m.target_kind))
  const out: { kind: string; source: string }[] = [
    { kind: 'envelope', source: generateEnvelopeModule(envelope) },
  ]
  for (const meta of kindMetas) {
    const source = SPEC_KINDS.has(meta.target_kind)
      ? generateKindModule(envelope, meta, allKinds)
      : generateRecordModule(meta, allKinds)
    out.push({ kind: meta.target_kind, source })
  }
  return out
}
