import type { AgentSpec, SkillSpec } from '../schema/index.js'

const MANAGED_MARKER = '<!-- hwh:managed: do not edit, generated by yhwh -->'

const yamlBool = (b: boolean): string => (b ? 'true' : 'false')

const yamlList = (xs: string[]): string => `[${xs.join(', ')}]`

const yamlMap = (entries: [string, string][]): string =>
  entries.map(([k, v]) => `${k}: ${v}`).join('\n')

export const renderAgentMd = (a: AgentSpec, body: string): string => {
  const fmEntries: [string, string][] = [
    ['name', a.id],
    ['description', JSON.stringify(a.description)],
    ['tools', a.tools.join(', ')],
    ['model', a.model],
  ]
  if (a.aura) {
    const auraLines = ['aura:']
    if (a.aura.doctrine) auraLines.push(`  doctrine: ${a.aura.doctrine}`)
    if (a.aura.resonance) auraLines.push(`  resonance: ${yamlList(a.aura.resonance)}`)
    if (a.aura.index) auraLines.push(`  index: ${yamlList(a.aura.index.map(String))}`)
    fmEntries.push(['__aura__', auraLines.slice(1).join('\n')])
  }
  const fm = fmEntries
    .filter(([k]) => k !== '__aura__')
    .map(([k, v]) => `${k}: ${v}`)
    .join('\n')
  const auraLines = a.aura
    ? [
        a.aura.doctrine ? `  doctrine: ${a.aura.doctrine}` : null,
        a.aura.resonance ? `  resonance: ${yamlList(a.aura.resonance)}` : null,
        a.aura.index ? `  index: ${yamlList(a.aura.index.map(String))}` : null,
      ].filter(Boolean)
    : null
  const aura = auraLines ? `\naura:\n${auraLines.join('\n')}` : ''
  return `---
${fm}${aura}
---
${MANAGED_MARKER}

${body.trim()}
`
}

export const renderSkillMd = (s: SkillSpec, body: string): string => {
  const fmEntries: [string, string][] = [
    ['name', s.id],
    ['description', JSON.stringify(s.description)],
  ]
  if (s.argument_hint) fmEntries.push(['argument-hint', JSON.stringify(s.argument_hint)])
  fmEntries.push(['user_invocable', yamlBool(s.user_invocable)])
  const fm = yamlMap(fmEntries)
  return `---
${fm}
---
${MANAGED_MARKER}

${body.trim()}
`
}
