import type { Graph } from '../graph.js'
import type { Spec } from '../schema/index.js'

export type RegistryJson = {
  version: 1
  generated_at: string
  specs: Record<string, Spec>
  by_kind: Record<string, string[]>
}

const generatedAt = (): string => {
  const epoch = process.env.SOURCE_DATE_EPOCH
  if (epoch && /^\d+$/.test(epoch)) return new Date(Number(epoch) * 1000).toISOString()
  return new Date().toISOString()
}

export const buildRegistryJson = (g: Graph): RegistryJson => {
  const specs: Record<string, Spec> = {}
  const by_kind: Record<string, string[]> = {}
  for (const [id, entry] of g.byId) {
    specs[id] = entry.spec
    const k = entry.spec.kind
    by_kind[k] = (by_kind[k] ?? []).concat(id).sort()
  }
  return {
    version: 1,
    generated_at: generatedAt(),
    specs,
    by_kind,
  }
}

export const emitRegistryTs = (json: RegistryJson): string => {
  const literal = JSON.stringify(json.specs, null, 2)
  return `// generated by yhwh — do not edit by hand
// generated_at: ${json.generated_at}
import type { Spec } from '../src/core/schema/index.js'

export const REGISTRY: Record<string, Spec> = ${literal} as const satisfies Record<string, Spec>

export const BY_KIND = ${JSON.stringify(json.by_kind, null, 2)} as const

export const get = (id: string): Spec | undefined => REGISTRY[id]
export const list = (kind?: Spec['kind']): Spec[] =>
  kind
    ? (BY_KIND[kind] ?? []).map((id) => REGISTRY[id]).filter((s): s is Spec => Boolean(s))
    : Object.values(REGISTRY)
`
}
