export const TYPES_TS = `// generated by yhwh — do not edit by hand
// re-exports the canonical Spec types derived from zod schemas in src/core/schema/

export type {
  Spec,
  AgentSpec,
  SkillSpec,
  FlowSpec,
  EntitySpec,
  HarnessSpec,
  RalphSpec,
  Kind,
} from '../src/core/schema/index.js'
`
