// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'

export const CommandFlagSchema = z.object({
  name: z.string(),
  takes_value: z.boolean().default(false),
})

export type CommandFlag = z.infer<typeof CommandFlagSchema>
