// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'

export const CrossRefSchema = z.object({
  rule_id: z.string(),
  description: z.string(),
  source: z.unknown(),
  target: z.unknown(),
  level: z.enum(['error', 'warning']).default('error'),
})

export type CrossRef = z.infer<typeof CrossRefSchema>
