// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'

export const EntitySchema = z.object({
  kind: z.literal('entity'),
  id: z.string().regex(/^[a-z][a-z0-9-]*$/),
  version: z.string().regex(/^\d+\.\d+\.\d+$/),
  status: z.enum(['draft', 'active', 'deprecated']),
  owner: z.string(),
  tags: z.array(z.string()).default([]),
  description: z.string(),
  fields: z.array(z.unknown()),
  invariants: z.array(z.string()).default([]),
})

export type EntitySpec = z.infer<typeof EntitySchema>
