// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'

export const EnvelopeFieldSchema = z.object({
  name: z.string(),
  type: z.unknown(),
  required: z.boolean().default(true),
  predicate: z.string().optional(),
  description: z.string(),
})

export type EnvelopeField = z.infer<typeof EnvelopeFieldSchema>
