// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'

export const KIND = z.enum([
  'agent',
  'skill',
  'flow',
  'entity',
  'harness',
  'ralph',
  'project',
  'meta-spec',
])
export type Kind = z.infer<typeof KIND>
export const ID = z.string().regex(/^[a-z][a-z0-9-]*$/)
export const SEMVER = z.string().regex(/^\d+\.\d+\.\d+$/)
export const STATUS = z.enum(['draft', 'active', 'deprecated'])

export const Envelope = z.object({
  kind: KIND,
  id: ID,
  version: SEMVER,
  status: STATUS,
  owner: z.string(),
  tags: z.array(z.string()).default([]),
})
