// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'

export const FlowSchema = z.object({
  kind: z.literal('flow'),
  id: z.string().regex(/^[a-z][a-z0-9-]*$/),
  version: z.string().regex(/^\d+\.\d+\.\d+$/),
  status: z.enum(['draft', 'active', 'deprecated']),
  owner: z.string(),
  tags: z.array(z.string()).default([]),
  description: z.string(),
  actors: z.array(z.string().regex(/^[a-z][a-z0-9-]*$/)).default([]),
  triggers: z.array(z.string()).default([]),
  next: z.array(z.string().regex(/^[a-z][a-z0-9-]*$/)).default([]),
})

export type FlowSpec = z.infer<typeof FlowSchema>
