// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'
import { CommandDeclSchema } from './command-decl.js'
import { GeneratorDeclSchema } from './generator-decl.js'
import { InputDeclSchema } from './input-decl.js'
import { ValidatorDeclSchema } from './validator-decl.js'

export const ProjectSchema = z.object({
  kind: z.literal('project'),
  id: z.string().regex(/^[a-z][a-z0-9-]*$/),
  version: z.string().regex(/^\d+\.\d+\.\d+$/),
  status: z.enum(['draft', 'active', 'deprecated']),
  owner: z.string(),
  tags: z.array(z.string()).default([]),
  description: z.string(),
  canonical_spec: z.string().optional(),
  inputs: z.array(InputDeclSchema).default([]),
  validators: z.array(ValidatorDeclSchema).default([]),
  generators: z.array(GeneratorDeclSchema).default([]),
  commands: z.array(CommandDeclSchema).default([]),
  waves_state_file: z.string().optional(),
})

export type ProjectSpec = z.infer<typeof ProjectSchema>
