// generated by yhwh (λY codegen) — do not edit by hand
// regenerate via: bun run hwh codegen-ts
import { z } from 'zod'

export const ValidatorDeclSchema = z.object({
  id: z.string(),
  layer: z.enum(['syntax', 'structural', 'semantic', 'meta-conformance', 'cross', 'fixed-point']),
})

export type ValidatorDecl = z.infer<typeof ValidatorDeclSchema>
